INSERT INTO account (name, position, university_id) VALUES
('Tamara Nelson-Fromm', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
('Will Koster', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
('Robert Altman', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
('Justin Ruan', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
('Elaine Houha', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
('Lily Holmes', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
('Annamarie Lunkes', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
('Alli Salmon', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
('Mitalee Bharadwaj', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
('Elizabeth Silva', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
('Grace Cao', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
('Ruby Reagan', 'Student', (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)'));

INSERT INTO enroll (account_id, course_id, university_id) VALUES
((SELECT id FROM account WHERE name = 'Tamara Nelson-Fromm'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
((SELECT id FROM account WHERE name = 'Will Koster'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
((SELECT id FROM account WHERE name = 'Robert Altman'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
((SELECT id FROM account WHERE name = 'Justin Ruan'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
((SELECT id FROM account WHERE name = 'Elaine Houha'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
((SELECT id FROM account WHERE name = 'Lily Holmes'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
((SELECT id FROM account WHERE name = 'Annamarie Lunkes'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
((SELECT id FROM account WHERE name = 'Alli Salmon'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
((SELECT id FROM account WHERE name = 'Mitalee Bharadwaj'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
((SELECT id FROM account WHERE name = 'Elizabeth Silva'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
((SELECT id FROM account WHERE name = 'Grace Cao'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)')),
((SELECT id FROM account WHERE name = 'Ruby Reagan'), (SELECT id FROM course WHERE crn = 'CS411'), (SELECT id FROM university WHERE name = 'University of Illinois (Urbana-Champaign)'));

INSERT INTO preference (account_id, project_id, ranking) VALUES
((SELECT id FROM account WHERE name = 'Tamara Nelson-Fromm'), (SELECT id FROM project WHERE name = 'myIllini'), 1),
((SELECT id FROM account WHERE name = 'Tamara Nelson-Fromm'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 2),
((SELECT id FROM account WHERE name = 'Tamara Nelson-Fromm'), (SELECT id FROM project WHERE name = 'MovieChat'), 3),
((SELECT id FROM account WHERE name = 'Will Koster'), (SELECT id FROM project WHERE name = 'myIllini'), 1),
((SELECT id FROM account WHERE name = 'Will Koster'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 2),
((SELECT id FROM account WHERE name = 'Will Koster'), (SELECT id FROM project WHERE name = 'MovieChat'), 3),
((SELECT id FROM account WHERE name = 'Robert Altman'), (SELECT id FROM project WHERE name = 'myIllini'), 1),
((SELECT id FROM account WHERE name = 'Robert Altman'), (SELECT id FROM project WHERE name = 'MovieChat'), 2),
((SELECT id FROM account WHERE name = 'Robert Altman'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 3),
((SELECT id FROM account WHERE name = 'Justin Ruan'), (SELECT id FROM project WHERE name = 'myIllini'), 1),
((SELECT id FROM account WHERE name = 'Justin Ruan'), (SELECT id FROM project WHERE name = 'MovieChat'), 2),
((SELECT id FROM account WHERE name = 'Justin Ruan'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 3),
((SELECT id FROM account WHERE name = 'Elaine Houha'), (SELECT id FROM project WHERE name = 'myIllini'), 1),
((SELECT id FROM account WHERE name = 'Elaine Houha'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 2),
((SELECT id FROM account WHERE name = 'Elaine Houha'), (SELECT id FROM project WHERE name = 'MovieChat'), 3),
((SELECT id FROM account WHERE name = 'Lily Holmes'), (SELECT id FROM project WHERE name = 'myIllini'), 1),
((SELECT id FROM account WHERE name = 'Lily Holmes'), (SELECT id FROM project WHERE name = 'MovieChat'), 2),
((SELECT id FROM account WHERE name = 'Lily Holmes'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 3),
((SELECT id FROM account WHERE name = 'Annamarie Lunkes'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 1),
((SELECT id FROM account WHERE name = 'Annamarie Lunkes'), (SELECT id FROM project WHERE name = 'myIllini'), 2),
((SELECT id FROM account WHERE name = 'Annamarie Lunkes'), (SELECT id FROM project WHERE name = 'MovieChat'), 3),
((SELECT id FROM account WHERE name = 'Alli Salmon'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 1),
((SELECT id FROM account WHERE name = 'Alli Salmon'), (SELECT id FROM project WHERE name = 'MovieChat'), 2),
((SELECT id FROM account WHERE name = 'Alli Salmon'), (SELECT id FROM project WHERE name = 'myIllini'), 3),
((SELECT id FROM account WHERE name = 'Mitalee Bharadwaj'), (SELECT id FROM project WHERE name = 'MovieChat'), 1),
((SELECT id FROM account WHERE name = 'Mitalee Bharadwaj'), (SELECT id FROM project WHERE name = 'myIllini'), 2),
((SELECT id FROM account WHERE name = 'Mitalee Bharadwaj'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 3),
((SELECT id FROM account WHERE name = 'Elizabeth Silva'), (SELECT id FROM project WHERE name = 'MovieChat'), 1),
((SELECT id FROM account WHERE name = 'Elizabeth Silva'), (SELECT id FROM project WHERE name = 'myIllini'), 2),
((SELECT id FROM account WHERE name = 'Elizabeth Silva'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 3),
((SELECT id FROM account WHERE name = 'Grace Cao'), (SELECT id FROM project WHERE name = 'MovieChat'), 1),
((SELECT id FROM account WHERE name = 'Grace Cao'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 2),
((SELECT id FROM account WHERE name = 'Grace Cao'), (SELECT id FROM project WHERE name = 'myIllini'), 3),
((SELECT id FROM account WHERE name = 'Ruby Reagan'), (SELECT id FROM project WHERE name = 'MovieChat'), 1),
((SELECT id FROM account WHERE name = 'Ruby Reagan'), (SELECT id FROM project WHERE name = 'myIllini'), 2),
((SELECT id FROM account WHERE name = 'Ruby Reagan'), (SELECT id FROM project WHERE name = 'Find Your Car!'), 3);
